### ISSUE TITLE
Initializing game crash

### ISSUE THREAD

**Issue by SeanChengN** [jabelar/MovingLightSource-1.12#1]
**Crash report**
https://pastebin.com/VNxDE6Ur

**To Reproduce**
Just open the game
If I remove CustomNPC mod, everything works fine.

**Version**
- Minecraft Version: 1.12.2
- Forge: 14.23.5.2768
- MovingLightSource: 1.0.4

**Comment by V10lator** [comment]
Same with Forge MultiPart CBE: https://paste.dimdev.org/ulapacuwum.mccrash

**Comment by jabelar** [comment]
Thanks, Same as other issue.
