### ISSUE TITLE
Epilepsy warning, tick-rate config

### ISSUE THREAD

**Issue by ghost** [jabelar/MovingLightSource-1.12#15]
I haven't had an actual fit, but I am affected by the flickering. Could this be resolved by adjusting the update rate (preferably in the config file)?

**Comment by jabelar** [comment]
It's interesting but I don't get any flickering in my testing. See the YouTube videos that are posted on the mod's page on CurseForge. Are you seeing something different than in my YouTube vids?

**Comment by ghost** [comment]
It's hard to tell in those video's since there is not a lot of large movements. When standing still or moving slowly the flickering-effect is not there or noticeable. But when walking, or worse,running it becomes unbearable (for me).

**Comment by jabelar** [comment]
I'll post some other videos, but I can sprint, fly around in creative, etc. with nothing I would call flicker.

Do you mind posting the specifications for your computer? I admit I usually am running on a high-performance machine.

I am looking at ways to potentially smooth things out, possibly helping in this case. Kinda hard to fix though since I can't reproduce a flicker problem when I run it...

**Comment by ghost** [comment]
First I did a test with just your mod installed, nothing else, and while it is less pronounced, it is still there and I do get a headache. (mind you, I have the same issue with the "dynamic lights" mod.)
I have:
i5-7500 CPU @ 3.40GHz, 4 Core
16 GB 2400 (6 GB assigned to MC)
NVIDIA GeForce GTX 1050 2GB

EDIT: I also have problems with fluorescent lights, so this may just be me. Don't go and try solve a problem if it is. :)

**Comment by jabelar** [comment]
Okay, well lighting in Minecraft is well "Minecrarft-like". That means there isn't a smooth transition between lighting at each block, but instead there is a "discrete" light level at each block. For example, if you're holding a light the block ahead of you will be at 13 light level and the one beyond at 12 and so forth, but when you move the 13 will turn to 14, the 12 to 13, etc.

If the "flickering" you're seeing is just the light changing levels then I probably can't fix that. If the flickering is actually "flashing" where the light briefly disappears completely that would be a bug. 

Does it look like the light is going away completely, or does it look like it is changing levels crudely?

**Comment by ghost** [comment]
I can't tell 100% for sure, but I think it is the brightness changing like you suspect. So nothing to be done I guess.
Does optifine use a different way of rendering the light since I never had this problem with that mod?

**Comment by jabelar** [comment]
Yes, optifine allows light levels transitions to be in-between values.

Note that you can run Optifine together with my mod and you can turn on dynamic lights there too. They don't conflict. The main advantage of my mod over optifine is that it changes the actual light level so light level effects (preventing mob spawns, melting snow, etc.) will happen. Optifine is purely cosmetic. 

But ultimately the lighting in my mod is sort of like chunk loading -- Minecraft has a sort of "blocky" way of doing things which can cause perceptible lags as things get updated.

**Comment by ghost** [comment]
Got it. Thanks.
