### ISSUE TITLE
Crash on 1.12.2

### ISSUE THREAD

**Issue by Boolyman** [jabelar/MovingLightSource-1.12#19]
Hey bud, loving the mod so far... works amazingly with Hardcore Darkness.

Got this crash, but did not realize you just did an update 6hrs ago.  Still gonna post the pastebin just in case its unrelated to something you fixed in this update.

https://pastebin.com/ezHAQ5SS

**Comment by jabelar** [comment]
Thanks, that seems to be same as issue #13 and so should be fixed now. Let me know if you see any more issues, and I really appreciate the feedback.
