### ISSUE TITLE
Shield interaction

### ISSUE THREAD

**Issue by VallenFrostweaver** [jabelar/MovingLightSource-1.12#3]
When I carry a shield in my off hand the shield disappears in first person view until I use it, though it is still there in 3rd person view.
v1.0.3
Forge 14.23.4.2739

**Comment by jabelar** [comment]
That is weird. I don't see the same thing. Here is video of me using shield in first person: https://www.youtube.com/watch?v=PiDJuTbLRdw

I honestly don't do anything with held items except check what they are, and I don't change rendering of anything (I just add "invisible" light sources).

Can you take a video to show what you're seeing?

**Comment by VallenFrostweaver** [comment]
I did more testing and I apologize. This wasnt the cause. Still trying to find it.
