### ISSUE TITLE
Trying to execute client code server-side

### ISSUE THREAD

**Issue by V10lator** [jabelar/MovingLightSource-1.12#5]
This causes a crash: https://pastebin.com/zEWrSjfU

**Comment by jabelar** [comment]
Ha! Yeah, a user asked me to have the config files translated to his native language so I added the translation but forgot that that would fail on the dedicated server. I was trying to be too fancy.

Will post a fix shortly.

**Comment by jabelar** [comment]
Okay should be fixed in 1.0.5.
